# Generated by Django 4.2.6 on 2023-10-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_pix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
