# Generated by Django 4.2.6 on 2023-10-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True, 'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
