# Generated by Django 4.2.6 on 2023-10-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
