# Generated by Django 4.2.6 on 2023-10-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_shopcart_color_shopcart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='quantity',
        ),
    ]
