# Generated by Django 4.2.6 on 2023-10-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_shopcart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='quantity',
            field=models.CharField(default='', max_length=200),
        ),
    ]
