# Generated by Django 4.2.6 on 2023-10-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_shopcart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopcart',
        ),
    ]
