# Generated by Django 4.2.6 on 2023-10-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_shopcart_amount_remove_shopcart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
