# Generated by Django 4.2.6 on 2023-11-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
